name: projectnbx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  lucide_icons_flutter: ^3.1.15
  google_fonts: ^8.2.1
  window_manager: ^0.5.2
  tray_manager: ^0.5.3
  hotkey_manager: ^0.2.3
  livekit_client: ^2.11.0
  permission_handler: ^13.0.1
  http: ^1.2.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
