# ==============================================================================
# Configurações do Linter de Go (GolangCI-Lint) - ProjectNBX Backend
# ==============================================================================

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - revive
    - misspell
    - gosec

linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
