services:
  # Banco de Dados Relacional PostgreSQL 16
  nbx_db:
    container_name: nbx_db
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '8190:5432'
    environment:
      POSTGRES_DB: nbx_stream
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nbx_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servidor SFU WebRTC LiveKit
  livekit:
    image: livekit/livekit-server:latest
    container_name: projectnbx-livekit
    restart: unless-stopped
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    ports:
      - "7880:7880" # Porta HTTP/WebSocket de sinalização
      - "7881:7881" # Porta TCP WebRTC
      - "50000-50020:50000-50020/udp" # Portas UDP WebRTC
    depends_on:
      - redis

  # Redis para estado e sessões
  redis:
    image: redis:7-alpine
    container_name: projectnbx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  pgdata: { }
