import 'package:flutter/material.dart';
import 'ux_nbx_models.dart';

final List<ServerData> uxServers = [
  const ServerData(
    id: "1",
    name: "Apex Predators",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 12,
    memberCount: 847,
    category: "Gaming",
    accentColor: Color(0xFF5865F2),
    unread: 3,
    activeChannel: "Ranked Match",
    description: "Comunidade focada em partidas ranqueadas e campeonatos de Apex Legends.",
  ),
  const ServerData(
    id: "2",
    name: "Dev Lounge",
    banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 4,
    memberCount: 234,
    category: "Programação",
    accentColor: Color(0xFF43B581),
    unread: 0,
    activeChannel: "Code Review",
    description: "Espaço para desenvolvedores compartilharem arquiteturas, PRs e tecnologias WebRTC.",
  ),
  const ServerData(
    id: "3",
    name: "Le Mans Ultimate",
    banner: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 8,
    memberCount: 512,
    category: "Racing Sim",
    accentColor: Color(0xFFFAA61A),
    unread: 7,
    activeChannel: "Live Stream",
    description: "Liga de endurance e simulação de corrida de alta fidelidade.",
  ),
  const ServerData(
    id: "4",
    name: "Minecraft Realm",
    banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 3,
    memberCount: 1204,
    category: "Survival",
    accentColor: Color(0xFF43B581),
    unread: 0,
    activeChannel: "Build Session",
    description: "Construções monumentais, redstone e sobrevivência cooperativa.",
  ),
  const ServerData(
    id: "5",
    name: "CS2 Tactics",
    banner: "https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 6,
    memberCount: 389,
    category: "FPS",
    accentColor: Color(0xFFF04747),
    unread: 2,
    activeChannel: "Scrim Room",
    description: "Táticas, line-ups de utilitários e treinos 5v5 competitivos.",
  ),
  const ServerData(
    id: "6",
    name: "Study Group",
    banner: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1400&h=420&fit=crop&auto=format",
    voiceCount: 1,
    memberCount: 156,
    category: "Estudo",
    accentColor: Color(0xFF9B59B6),
    unread: 0,
    activeChannel: "Foco Total",
    description: "Salas de silêncio e pomodoro para foco absoluto em estudos e projetos.",
  ),
];

final List<String> uxCategories = [
  "TODOS",
  "Gaming",
  "Programação",
  "Racing Sim",
  "FPS",
  "Survival",
  "Estudo",
];

final Map<String, List<String>> uxServerPresences = {
  "1": ["Lucas Menezes", "Rafael Alves", "Ana Beatriz", "Thiago F."],
  "2": ["Rafael Alves", "Maria Costa", "João Ferreira"],
  "3": ["Marina Silva", "Pedro Lima", "Camila Souza", "André R."],
  "4": ["Pedro Kim", "João Ferreira", "Bia Martins"],
  "5": ["Lucas Menezes", "Thiago F.", "Rafael Alves"],
  "6": ["Ana Beatriz", "Marina Silva"],
};

final List<ActivityData> uxActivities = [
  const ActivityData(
    id: "1",
    initials: "LM",
    user: "Lucas Menezes",
    action: "abriu um lobby de CS2",
    server: "Apex Predators",
    serverId: "5",
    time: "2 min atrás",
    type: "voice",
    color: Color(0xFF5865F2),
  ),
  const ActivityData(
    id: "2",
    initials: "MS",
    user: "Marina Silva",
    action: "está ao vivo em Le Mans Ultimate",
    server: "Le Mans Ultimate",
    serverId: "3",
    time: "5 min atrás",
    type: "stream",
    color: Color(0xFFFAA61A),
  ),
  const ActivityData(
    id: "3",
    initials: "PK",
    user: "Pedro, Ana e João",
    action: "3 amigos ativos",
    server: "Minecraft Realm",
    serverId: "4",
    time: "12 min atrás",
    type: "group",
    color: Color(0xFF43B581),
  ),
  const ActivityData(
    id: "4",
    initials: "RA",
    user: "Rafael Alves",
    action: "entrou na chamada de voz",
    server: "Dev Lounge",
    serverId: "2",
    time: "18 min atrás",
    type: "voice",
    color: Color(0xFF43B581),
  ),
  const ActivityData(
    id: "5",
    initials: "AB",
    user: "Ana Beatriz",
    action: "iniciou uma study stream",
    server: "Study Group",
    serverId: "6",
    time: "24 min atrás",
    type: "stream",
    color: Color(0xFF9B59B6),
  ),
  const ActivityData(
    id: "6",
    initials: "TF",
    user: "Thiago F.",
    action: "criou um clip épico",
    server: "Apex Predators",
    serverId: "1",
    time: "31 min atrás",
    type: "clip",
    color: Color(0xFF5865F2),
  ),
];

final List<MentionData> uxMentions = [
  const MentionData(
    id: "1",
    server: "Apex Predators",
    channel: "#estratégia",
    user: "Lucas",
    preview: "@você olha esse clip, absurdo!",
    time: "3m",
  ),
  const MentionData(
    id: "2",
    server: "CS2 Tactics",
    channel: "#recrutamento",
    user: "Rafael",
    preview: "@você pode hoje às 21h para o scrim?",
    time: "27m",
  ),
  const MentionData(
    id: "3",
    server: "Dev Lounge",
    channel: "#ajuda",
    user: "Maria",
    preview: "@você já viu essa PR? preciso de review",
    time: "1h",
  ),
];

final List<VoiceUserData> uxVoiceUsers = [
  const VoiceUserData(
    id: "lm",
    name: "LucasM",
    initials: "LM",
    color: Color(0xFF5865F2),
    speaking: true,
    muted: false,
    isStreaming: false,
  ),
  const VoiceUserData(
    id: "ms",
    name: "Marina_S",
    initials: "MS",
    color: Color(0xFFFAA61A),
    speaking: false,
    muted: false,
    isStreaming: true,
  ),
  const VoiceUserData(
    id: "pk",
    name: "Pedro_K",
    initials: "PK",
    color: Color(0xFF43B581),
    speaking: false,
    muted: true,
    isStreaming: false,
  ),
];

final List<ChannelData> uxChannels = [
  ChannelData(
    id: "t1",
    name: "geral",
    type: ChannelKind.textVoice,
    unread: 0,
    users: uxVoiceUsers,
    description: "Discussões gerais e voz ativa do servidor",
  ),
  const ChannelData(
    id: "t2",
    name: "anúncios",
    type: ChannelKind.text,
    unread: 2,
    description: "Novidades oficiais, comunicados e cronogramas",
  ),
  const ChannelData(
    id: "t5",
    name: "imagens",
    type: ChannelKind.images,
    unread: 0,
    description: "Galeria de screenshots, setups e fotos da comunidade",
  ),
  const ChannelData(
    id: "t6",
    name: "arquivos",
    type: ChannelKind.files,
    unread: 0,
    description: "Documentos, regras, replays e arquivos compartilhados",
  ),
];

final List<MemberData> uxMembers = [
  const MemberData(
    id: "m1",
    name: "DarkLord_X",
    initials: "DX",
    color: Color(0xFFFAA61A),
    status: "online",
    role: "Admin",
    roleColor: Color(0xFFFAA61A),
    playing: "CS2",
  ),
  const MemberData(
    id: "m2",
    name: "Marina_S",
    initials: "MS",
    color: Color(0xFFFAA61A),
    status: "streaming",
    role: "Mod",
    roleColor: Color(0xFF43B581),
    playing: "Le Mans Ultimate",
  ),
  const MemberData(
    id: "m3",
    name: "LucasM",
    initials: "LM",
    color: Color(0xFF5865F2),
    status: "online",
    role: "VIP",
    roleColor: Color(0xFF9B59B6),
    playing: "CS2",
  ),
  const MemberData(
    id: "m4",
    name: "Rafael_A",
    initials: "RA",
    color: Color(0xFF9B59B6),
    status: "online",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
  ),
  const MemberData(
    id: "m5",
    name: "Ana_B",
    initials: "AB",
    color: Color(0xFFFAA61A),
    status: "online",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
  ),
  const MemberData(
    id: "m6",
    name: "Pedro_K",
    initials: "PK",
    color: Color(0xFF43B581),
    status: "online",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
    playing: "Minecraft",
  ),
  const MemberData(
    id: "m7",
    name: "João_F",
    initials: "JF",
    color: Color(0xFF5865F2),
    status: "idle",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
  ),
  const MemberData(
    id: "m8",
    name: "Thiago_R",
    initials: "TR",
    color: Color(0xFFF04747),
    status: "online",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
    playing: "Apex",
  ),
  const MemberData(
    id: "m9",
    name: "Camila_S",
    initials: "CS",
    color: Color(0xFF9B59B6),
    status: "dnd",
    role: "Membro",
    roleColor: Color(0xFF8E9297),
  ),
];

final List<ChatMessageData> uxMessages = [
  const ChatMessageData(
    id: "msg1",
    author: "DarkLord_X",
    initials: "DX",
    color: Color(0xFFFAA61A),
    time: "10:23",
    content: "Pessoal, campeonato interno começa sábado às 21h 🏆",
    isMe: false,
    reactions: {"🔥": 4, "👑": 2},
  ),
  const ChatMessageData(
    id: "msg2",
    author: "Marina_S",
    initials: "MS",
    color: Color(0xFFFAA61A),
    time: "10:25",
    content: "Já estou confirmada! Quem mais vai participar?",
    isMe: false,
    reactions: {"🏎️": 3},
  ),
  const ChatMessageData(
    id: "msg3",
    author: "LucasM",
    initials: "LM",
    color: Color(0xFF5865F2),
    time: "10:26",
    content: "Tô dentro! Qual vai ser o formato?",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg4",
    author: "DarkLord_X",
    initials: "DX",
    color: Color(0xFFFAA61A),
    time: "10:28",
    content: "5v5, melhor de 3, mapas na votação da comunidade antes do evento",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg5",
    author: "Rafael_A",
    initials: "RA",
    color: Color(0xFF9B59B6),
    time: "10:30",
    content: "Boa demais, esse fim de semana vai ser épico 🚀",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg6",
    author: "Ana_B",
    initials: "AB",
    color: Color(0xFFFAA61A),
    time: "10:31",
    content: "Confirmo presença! Alguém pode me dar carry? 😅",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg7",
    author: "Pedro_K",
    initials: "PK",
    color: Color(0xFF43B581),
    time: "10:33",
    content: "@Ana_B relaxa, tamo junto no mesmo time!",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg8",
    author: "Você",
    initials: "EU",
    color: Color(0xFF5865F2),
    time: "10:35",
    content: "@todos estou dentro! pode contar comigo no sábado 👍",
    isMe: true,
  ),
  const ChatMessageData(
    id: "msg9",
    author: "Marina_S",
    initials: "MS",
    color: Color(0xFFFAA61A),
    time: "10:36",
    content: "gg, time completo então. Hora de treinar 🎮",
    isMe: false,
  ),
  const ChatMessageData(
    id: "msg10",
    author: "DarkLord_X",
    initials: "DX",
    color: Color(0xFFFAA61A),
    time: "10:40",
    content: "Criei o evento no servidor, confiram nos anúncios. Vai rolar transmissão ao vivo!",
    isMe: false,
  ),
];

final List<BoardData> uxBoardItems = [
  const BoardData(
    id: "b1",
    type: "announcement",
    title: "🏆 Campeonato Interno — Sábado",
    content: "5v5 Melhor de 3 • Começa às 21h • Transmissão ao vivo pela Marina_S",
    date: "Sáb, 22 Ago • 21:00",
    author: "DarkLord_X",
    pinned: true,
  ),
  const BoardData(
    id: "b2",
    type: "event",
    title: "🎯 Treino Coletivo — Quinta-Feira",
    content: "Treino de warm-up e revisão de callouts. Todas as ranks bem-vindas.",
    date: "Qui, 20 Ago • 20:00",
    author: "Marina_S",
    pinned: false,
  ),
  const BoardData(
    id: "b3",
    type: "reminder",
    title: "📜 Regras do Servidor",
    content: "Respeite todos os membros. Sem flaming. Boa sorte e bom jogo!",
    date: "Fixado sempre",
    author: "DarkLord_X",
    pinned: true,
  ),
];

final List<ImageGalleryItem> uxImageGallery = [
  const ImageGalleryItem(
    id: "img-1",
    title: "Largada da corrida",
    author: "Marina_S",
    src: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=720&h=480&fit=crop&auto=format",
  ),
  const ImageGalleryItem(
    id: "img-2",
    title: "Setup do Lucas",
    author: "LucasM",
    src: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=720&h=480&fit=crop&auto=format",
  ),
  const ImageGalleryItem(
    id: "img-3",
    title: "Campeonato interno",
    author: "DarkLord_X",
    src: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=720&h=480&fit=crop&auto=format",
  ),
  const ImageGalleryItem(
    id: "img-4",
    title: "Clips da semana",
    author: "Pedro_K",
    src: "https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=720&h=480&fit=crop&auto=format",
  ),
];

final Map<String, List<FileExplorerItem>> uxFileExplorer = {
  "root": [
    const FileExplorerItem(
      id: "folder-media",
      name: "Mídia do servidor",
      kind: "folder",
      detail: "24 itens",
      updated: "hoje",
    ),
    const FileExplorerItem(
      id: "folder-campeonatos",
      name: "Campeonatos",
      kind: "folder",
      detail: "8 itens",
      updated: "ontem",
    ),
    const FileExplorerItem(
      id: "rules",
      name: "regras-do-servidor.pdf",
      kind: "file",
      detail: "PDF • 1,8 MB",
      updated: "há 2 h",
    ),
    const FileExplorerItem(
      id: "schedule",
      name: "calendario-agosto.xlsx",
      kind: "file",
      detail: "XLSX • 248 KB",
      updated: "há 1 d",
    ),
  ],
  "folder-media": [
    const FileExplorerItem(
      id: "clips",
      name: "Clips",
      kind: "folder",
      detail: "16 itens",
      updated: "hoje",
    ),
    const FileExplorerItem(
      id: "screenshots",
      name: "Screenshots",
      kind: "folder",
      detail: "8 itens",
      updated: "há 2 d",
    ),
    const FileExplorerItem(
      id: "poster",
      name: "poster-campeonato.png",
      kind: "file",
      detail: "PNG • 3,2 MB",
      updated: "há 3 h",
    ),
  ],
  "clips": [
    const FileExplorerItem(
      id: "clip-final",
      name: "largada-final.mp4",
      kind: "file",
      detail: "MP4 • 48 MB",
      updated: "hoje",
    ),
    const FileExplorerItem(
      id: "clip-sector",
      name: "sector-2.webm",
      kind: "file",
      detail: "WEBM • 22 MB",
      updated: "hoje",
    ),
  ],
  "screenshots": [
    const FileExplorerItem(
      id: "shot-setup",
      name: "setup-lucas.png",
      kind: "file",
      detail: "PNG • 1,4 MB",
      updated: "há 2 d",
    ),
    const FileExplorerItem(
      id: "shot-podium",
      name: "podio-campeonato.jpg",
      kind: "file",
      detail: "JPG • 2,6 MB",
      updated: "há 2 d",
    ),
  ],
  "folder-campeonatos": [
    const FileExplorerItem(
      id: "regulamento",
      name: "regulamento-5v5.pdf",
      kind: "file",
      detail: "PDF • 2,1 MB",
      updated: "ontem",
    ),
    const FileExplorerItem(
      id: "times",
      name: "times-confirmados.csv",
      kind: "file",
      detail: "CSV • 18 KB",
      updated: "ontem",
    ),
  ],
};
